In [1]:
import numpy as np

# Creating numpy array

In [2]:
data=[1,2,3]

In [3]:
data

[1, 2, 3]

In [4]:
type(data)

list

In [5]:
arr=np.array(data)

In [6]:
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr=np.array([1,2,3])

In [9]:
arr

array([1, 2, 3])

In [10]:
type(arr)

numpy.ndarray

# Built in Methods

# Arange

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,step=2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,10,step=0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [17]:
np.arange(0,10,step=1.5)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [21]:
np.arange(0,20,step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Zeros & Ones

In [23]:
np.zeros(shape=2)

array([0., 0.])

In [24]:
np.ones(shape=5)

array([1., 1., 1., 1., 1.])

In [29]:
np.zeros(shape=(4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones(shape=5,dtype=int)

array([1, 1, 1, 1, 1])

# Linspace

In [38]:
np.linspace(start=0,stop=10,num=3,dtype=int)

array([ 0,  5, 10])

# Eye

In [39]:
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(N=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.eye(N=4,M=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [44]:
np.eye(N=4,M=6,k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

# Random

# Rand

In [49]:
np.random.rand(2)

array([0.35550667, 0.10761183])

In [52]:
np.random.rand(5,5)

array([[0.16528432, 0.80111561, 0.19189445, 0.17711129, 0.81094357],
       [0.38222137, 0.75023725, 0.72681952, 0.62984786, 0.53692877],
       [0.01044934, 0.66693448, 0.36751531, 0.50127564, 0.77479363],
       [0.14212644, 0.77895039, 0.87224726, 0.97104034, 0.62166068],
       [0.83062619, 0.77670518, 0.87430058, 0.88637364, 0.10896224]])

# Randn

In [54]:
np.random.randn(2)

array([-0.46074764,  0.0356413 ])

In [55]:
np.random.randn(5,5)

array([[ 0.79296937, -1.09485962,  1.33044995, -0.2830266 ,  0.15045676],
       [ 2.02378861, -0.89797671,  1.30705614, -1.21425731, -0.28255866],
       [ 0.21568551,  0.73518482, -0.26748986,  0.4030703 , -0.9812717 ],
       [-0.70734311, -0.44976136, -0.03575396, -0.09815123,  1.04818931],
       [-0.65197445, -1.61551397,  0.25805173,  0.08507239,  0.85062463]])

In [57]:
np.random.randn(5,5)+4

array([[2.96322698, 4.35580095, 4.85007921, 3.61715896, 3.98806489],
       [3.7677254 , 4.29667147, 2.9073211 , 4.15687729, 3.06303357],
       [3.27746397, 4.65148173, 2.99760297, 3.40235734, 2.37074477],
       [3.40870464, 4.8453637 , 4.40383334, 1.74237854, 3.98408871],
       [3.66501652, 5.70236618, 3.15593038, 3.95704383, 3.12990499]])

# Randint

In [59]:
np.random.randint(5)

2

In [60]:
np.random.randint(5,10)


7

In [61]:
np.random.randint(5,20,4)

array([ 8, 10, 14,  8])

In [64]:
np.random.randint(3,size=(2,4))

array([[1, 2, 2, 1],
       [0, 0, 0, 1]])

# Array Attributes & Methods

# Reshape

In [82]:
arr=np.arange(16)

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [84]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Shape

In [85]:
arr.shape

(16,)

In [86]:
arr.reshape(1,16).shape

(1, 16)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [88]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


# Dtype

In [89]:
arr.dtype

dtype('int32')

# Indexing & Selection

In [91]:
arr=np.arange(0,10)

In [92]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
arr[-4]

6

In [98]:
arr[:5]

array([0, 1, 2, 3, 4])

In [99]:
arr[1:5]

array([1, 2, 3, 4])

# Broadcasting

In [100]:
arr[0:5]=10

In [101]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [103]:
arr=np.arange(0,10)

In [104]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
slice1=arr[0:5]

In [106]:
slice1

array([0, 1, 2, 3, 4])

In [107]:
slice1[:]=4

In [108]:
slice1

array([4, 4, 4, 4, 4])

In [109]:
copy_arr=arr.copy()

In [110]:
copy_arr

array([4, 4, 4, 4, 4, 5, 6, 7, 8, 9])

# Indexing 2D Array/Matrix

In [111]:
arr_2d=np.array(([10,20,30],[34,56,54],[54,89,23]))

In [112]:
arr_2d

array([[10, 20, 30],
       [34, 56, 54],
       [54, 89, 23]])

In [113]:
arr_2d.shape

(3, 3)

In [114]:
arr_2d[0]

array([10, 20, 30])

In [115]:
arr_2d[-1]

array([54, 89, 23])

In [116]:
arr_2d[0][1]

20

In [117]:
arr_2d[0,1]

20

In [118]:
arr_2d[:,:-1]

array([[10, 20],
       [34, 56],
       [54, 89]])

In [119]:
arr_2d[:,1]

array([20, 56, 89])

# Fancy Indexing

In [121]:
arr=np.zeros((3,3))

In [122]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [123]:
arr_len=arr.shape[0]

In [124]:
arr_len

3

In [127]:
for i in range(arr_len):
    arr[i]=i
    print(arr[i])

[0. 0. 0.]
[1. 1. 1.]
[2. 2. 2.]


# Selection

In [128]:
arr=np.arange(0,11)

In [129]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
arr>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

# Numpy Operations

# Arithmetic

In [138]:
arr1=np.arange(0,10)

In [133]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
arr1+arr1 #addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [137]:
arr1-arr1 #subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [139]:
arr1*arr1 #multiplication

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [140]:
arr1/arr1 #divison

<ipython-input-140-e2b73f1fec4a>:1: RuntimeWarning: invalid value encountered in true_divide
  arr1/arr1 #divison


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [143]:
arr1=np.arange(0,10)

In [144]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
arr1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [147]:
arr1**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

# Universal Array Function

In [148]:
arr1=np.arange(0,10)

In [149]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [150]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [151]:
np.max(arr1)

9

In [152]:
np.min(arr1)

0

In [153]:
np.log(arr1)

<ipython-input-153-ee4fb0b16e6c>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [166]:
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])

In [167]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [168]:
arr.shape

(3, 3)

In [169]:
arr1=np.array([[4,5,6]])

In [170]:
arr1

array([[4, 5, 6]])

In [171]:
arr1.shape

(1, 3)

# Append

In [172]:
np.append(arr=arr,values=arr1,axis=0)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Concatenate

In [174]:
new=np.concatenate((arr,arr1),axis=0)

In [175]:
new.shape

(4, 3)

# Stack 

In [176]:
np.vstack((arr,arr1))

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [182]:
arr2=np.array([[1],[2],[3]])

In [183]:
np.hstack((arr,arr2))

array([[1, 2, 3, 1],
       [2, 3, 4, 2],
       [3, 4, 5, 3]])