# Decision Tree Regressor

In [92]:
import pandas as pd
import numpy as np

In [93]:
df=pd.read_csv('50_Startups.csv')

In [94]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [95]:
#missing values
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [97]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [98]:
df.describe()

R&D Spend  Administration  Marketing Spend         Profit
count     108.000000      108.000000       108.000000     108.000000
mean    74959.338704   121750.788889    214952.664722  113523.760000
std     44996.368152    27322.385654    117937.942120   38991.013654
min         0.000000    51283.140000         0.000000   14681.400000
25%     38558.510000   105077.645000    134050.070000   90708.190000
50%     75791.365000   122699.795000    239452.750000  109543.120000
75%    101913.080000   145077.580000    298664.470000  141585.520000
max    165349.200000   182645.560000    471784.100000  192261.830000

# Label Encoding

In [99]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(df.State.value_counts())
df['State']=le.fit_transform(df['State'])


New York      39
California    36
Florida       33
Name: State, dtype: int64


In [100]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [101]:
print(df.State.value_counts())

2    39
0    36
1    33
Name: State, dtype: int64


# Independent & Dependent

In [102]:
#independent variable
x=df.iloc[:,0:4].values

In [103]:
x

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 2.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 1.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 2.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 2.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 1.0000000e+00],
       [1.0067196e+05, 9.1790610e+04, 2.4974455e+05, 0.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 1.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00],
       [1.1994324e+05, 1.5654742e+

In [104]:
type(x)

numpy.ndarray

In [105]:
#dependent variable
y=df.iloc[:,4:5].values

In [106]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ],


In [107]:
x.shape

(108, 4)

In [108]:
y.shape

(108, 1)

# One Hot Encoding

In [109]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
z=ohe.fit_transform(x[:,3:4]).toarray()


In [110]:
x=np.delete(x,3,axis=1)
x=np.concatenate((z,x),axis=1)

In [111]:
x.shape

(108, 6)

In [112]:
x

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

# Train ,Test & Split

In [113]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# Model Building

In [114]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [115]:
dtrpred=dtr.predict(x_test)

In [116]:
dtrpred

array([ 42559.73, 146121.95,  90708.19, 191050.39, 108552.04, 144259.4 ,
       124266.9 , 155752.6 , 126992.93,  42559.73, 101004.64, 110352.25,
        42559.73, 111313.02,  89949.14, 134307.35, 134307.35,  96479.51,
        49490.75, 129917.04, 132602.65, 152211.77])

In [117]:
y_test

array([[ 64926.08],
       [146121.95],
       [ 90708.19],
       [191050.39],
       [108552.04],
       [144259.4 ],
       [124266.9 ],
       [155752.6 ],
       [126992.93],
       [ 42559.73],
       [101004.64],
       [110352.25],
       [ 64926.08],
       [111313.02],
       [ 89949.14],
       [134307.35],
       [134307.35],
       [ 96712.8 ],
       [ 49490.75],
       [129917.04],
       [132602.65],
       [152211.77]])

In [118]:
from sklearn.metrics import r2_score
dtrscore=r2_score(dtrpred,y_test)

In [119]:
dtrscore

0.9703878406939315

In [121]:
profit=dtr.predict([[101913.08,91790.61,264346.06,0,1,2]])

In [122]:
profit

array([35673.41])

# Random Forest Regressor

In [134]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(n_estimators=10,random_state=0)
rfr.fit(x_train,y_train)

<ipython-input-134-aa3dc07b6f95>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfr.fit(x_train,y_train)


RandomForestRegressor(n_estimators=10, random_state=0)

In [135]:
rfrpred=rfr.predict(x_test)

In [136]:
rfrpred

array([ 38496.054, 145935.695,  89645.383, 186976.19 , 120138.537,
       142268.99 , 125998.762, 155913.443, 126992.93 ,  38491.584,
       101860.555, 110190.424,  38496.054, 116570.838,  91968.133,
       133303.305, 133303.305,  96656.514,  43810.498, 131715.226,
       137995.024, 139351.273])

In [137]:
dtrpred

array([ 42559.73, 146121.95,  90708.19, 191050.39, 108552.04, 144259.4 ,
       124266.9 , 155752.6 , 126992.93,  42559.73, 101004.64, 110352.25,
        42559.73, 111313.02,  89949.14, 134307.35, 134307.35,  96479.51,
        49490.75, 129917.04, 132602.65, 152211.77])

In [138]:
rfrscore=r2_score(rfrpred,y_test)

In [139]:
rfrscore

0.9474099343807247

In [140]:
dtrscore

0.9703878406939315

# Logisitic Regression